name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_FRAMEWORK: net8.0
  DOTNET_VERSION: 8.0.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🚧 Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work

      - name: 🔨 Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 🏗️ Run dotnet build
        id: build
        run: dotnet build -c release

      - name: 🎨 Run dotnet format
        id: format
        run: dotnet format --verbosity diagnostic --verify-no-changes --no-restore

      - name: 🧪 Run dotnet test
        id: test
        run: dotnet test -c release --no-restore
